import {generateKeyPairSync} from "node:crypto";
import {existsSync, readFileSync, writeFileSync} from "node:fs";
import {logger} from "@terreno/api";

// Adds a development GRANT_SIGNING_PRIVATE_KEY to backend/.env when one is not set.
// Production keys are provisioned as secrets, never generated by this script.
const envPath = new URL("../../.env", import.meta.url).pathname;
const current = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";

if (/^GRANT_SIGNING_PRIVATE_KEY=.+/m.test(current)) {
  logger.info("GRANT_SIGNING_PRIVATE_KEY already set in backend/.env");
} else {
  const {privateKey} = generateKeyPairSync("ed25519");
  const encoded = privateKey.export({format: "der", type: "pkcs8"}).toString("base64url");
  const separator = current === "" || current.endsWith("\n") ? "" : "\n";
  writeFileSync(envPath, `${current}${separator}GRANT_SIGNING_PRIVATE_KEY=${encoded}\n`);
  logger.info("Wrote a development GRANT_SIGNING_PRIVATE_KEY to backend/.env");
}
